### ISSUE TITLE
Dependency `chokidar` is not bundled

### ISSUE THREAD

**Issue by philp** [cypress-io/cypress-watch-preprocessor#4]
- Operating System: MacOS
- Cypress Version: 3.4.1
- Browser Version: Chrome

### Is this a Feature or Bug?

Bug

### Current behavior:

Once the packaged is installed, it will fail to run because of a missing dependency: `chokidar`

### Desired behavior:

It should run without an exception. I was able to achieve this by manually adding `chokidar` to my project dependencies.

### How to reproduce:

Install cypress, then install and configure this plugin based on the README instructions.

**Comment by chrisbreiding** [comment]
Thanks for submitting this issue. I think we didn't catch this because we have `chokidar-cli` as a dev dependency, so when developing, `chokidar` gets added transiently. I'll get a patch out to fix this soon.
